name: CI Frontend

# Se déclenche sur chaque push et chaque PR, toutes branches
on:
  push:
    branches: ["master"]

# On execute ces instructions
jobs:
  mount_container:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Docker compose up
        run: "docker compose up"
