name: CI Frontend


on:
  push:
    branches: ["master"]


jobs:

  mount_container:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Sudo apt update
        uses: "sudo apt update"

      - name: Docker compose up
        run: "docker compose up -d"
